### ISSUE TITLE
Provide a way to fake FeatureFlagsState in tests

### ISSUE THREAD

**Issue by ashmind** [launchdarkly/dotnet-server-sdk#125]
**Is your feature request related to a problem? Please describe.**
I have some code that displays state from `FeatureFlagsState` and I would like to unit-test this code. However `FeatureFlagsState` constructors are internal at the moment, so it's hard to write a unit-test on code that uses it.

**Describe the solution you'd like**
I would like to be able to create `FeatureFlagsState` in tests (with some fake metadata). Specific approach for that is not very important. Some options: make constructors public, or provide builder/factory to create it, or add empty ctor and make class virtual so it can be mocked.

**Describe alternatives you've considered**
I can create it with reflection, but it's complicated and brittle.

**Comment by eli-darkly** [comment]
Yes, that's reasonable.

**Comment by eli-darkly** [comment]
The 5.12.0 release adds a builder for this.
