### ISSUE TITLE
Link to source repo from Nuget package

### ISSUE THREAD

**Issue by fjmorel** [launchdarkly/dotnet-server-sdk#129]
**Is your feature request related to a problem? Please describe.**
No easy way to get to the release notes from Nuget Package Manager

**Describe the solution you'd like**
- Add project URL to Nuget package linking to this repo, where I can click on CHANGELOG.md to see release notes.

**Describe alternatives you've considered**
Googling for the repo every time a new release comes out.

**Additional context**

Source Link support would also be great: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

**Comment by eli-darkly** [comment]
Sorry, that was an unintentional omission - we normally do include repo URLs in our SDK artifacts. That's easy to fix; Source Link might take a little longer.

**Comment by eli-darkly** [comment]
Sorry this fell through the cracks. We did update the project metadata for the upcoming 6.0.0 release, and if we do any further 5.x maintenance releases they will also have it.
