### ISSUE TITLE
Update Flags

### ISSUE THREAD

**Issue by joerter** [launchdarkly/dotnet-server-sdk#130]
Does the dotnet-server-sdk have the ability to update the value of feature or flags or only to evaluate them? 

If not, what is the reason for this and what is the recommended path to updating flags? Should I use the API directly?

Thank you!

**Comment by eli-darkly** [comment]
All of the LaunchDarkly SDKs are for the purpose of evaluating flags. They do not send any data to LaunchDarkly except for analytics events and diagnostics. The service endpoints that deliver data to SDKs are deliberately separate from the ones for other LaunchDarkly functions, and the data model is not the same (for instance, SDKs only interact with the flag configuration for a single environment).

To update flags you would either use the API directly, or one of the generated client libraries for the API as described [here](https://apidocs.launchdarkly.com/reference#open-api-swagger).
