### ISSUE TITLE
Add support for application metadata

### ISSUE THREAD

**Issue by burck1** [launchdarkly/dotnet-server-sdk#165]
**Is your feature request related to a problem? Please describe.**
I would love to see the SDK support recording [application metadata](https://docs.launchdarkly.com/sdk/features/app-config).

**Describe the solution you'd like**
Similar to the other [Server-side SDKs](https://docs.launchdarkly.com/sdk/features/app-config#server-side-sdks), it would be nice if the `LdClient` configuration and configuration builder supported setting application metadata.

**Describe alternatives you've considered**
Alternatively, application metadata could be added as a context data.

**Comment by kinyoklion** [comment]
Hello @burck1,

Thank you for the issue. We plan to do this, but I do not have a specific timeline I can provide.

Thank you,
Ryan

_Filed internally as 183475_

**Comment by burck1** [comment]
Thanks for the prompt response! I look forward to hearing more about it in the future.

**Comment by kinyoklion** [comment]
@burck1 This has been released in the latest major version.

Thank you,
Ryan
