### ISSUE TITLE
Add `IsOffline()` to `ILdClient`

### ISSUE THREAD

**Issue by justindbaur** [launchdarkly/dotnet-server-sdk#169]
**Is your feature request related to a problem? Please describe.**
When using Dependency Injection or writing unit tests it's common to use an interface as your constructor argument so that it can easily be mocked. Since `LdClient` is `sealed` it is not as easily mocked. Yet the concrete type is still required if you want to check `.IsOffline()`. My proposal is to add that as part of the `ILdClient` interface. 

**Describe the solution you'd like**
```diff
namespace LaunchDarkly.Sdk.Server.Interfaces
{
    public interface ILdClient
    {
+        bool IsOffline();
    }
}
```

LdClient already implements this method so no additional work would be needed, as far as I can tell in the open source world no one else implements a custom `ILdClient` ([source](https://grep.app/search?q=ILdClient&case=true)) so the amount of people this would affect should be negligible. But it would require other implementers to add this method if they did. 

**Describe alternatives you've considered**
```diff
namespace LaunchDarkly.Sdk.Server.Interfaces
{
    public interface ILdClient
    {
+        bool IsOffline()
+        {
+            return true; // or false
+        }
    }
}
```
This alternative takes advantage of [Default Interface Implementation](https://devblogs.microsoft.com/dotnet/default-implementations-in-interfaces/) such that any downstream creators of their custom `ILdClient` would not have to add their own implementation of this method.

**Additional context**
I'd be more than willing to create a PR for this change if one of the designs is chosen.

**Comment by kinyoklion** [comment]
Hello @justindbaur,

I agree that it is unfortunate that this is not in the interface. I do think, in the interface we should probably just make it an offline property.

Reason being that IldClient for the client-side dotnet SDK already defines such a property, and it would be nice to keep it consistent.

The client-side definition:
```
        /// <summary>
        /// Indicates whether the SDK is configured to be always offline.
        /// </summary>
        /// <remarks>
        /// <para>
        /// This is initially <see langword="true"/> if you set it to <see langword="true"/> in the configuration with
        /// <see cref="ConfigurationBuilder.Offline(bool)"/>. However, you can change it at any time to allow the client
        /// to go online, or force it to go offline, using <see cref="SetOffline(bool, TimeSpan)"/> or
        /// <see cref="SetOfflineAsync(bool)"/>.
        /// </para>
        /// <para>
        /// When <see cref="Offline"/> is <see langword="false"/>, the SDK connects to LaunchDarkly if possible, but
        /// this does not guarantee that the connection is successful. There is currently no mechanism to detect whether
        /// the SDK is currently connected to LaunchDarkly.
        /// </para>
        /// </remarks>
        bool Offline { get; }
```
(One comment for this doesn't apply to the server side).

That does leave the unfortunate situation that the interface method is different than the current concrete implementation. Which I think we could start guiding, with a comment indicating it will be deprecated, and then eventually deprecate.

So,
1. `bool Offline {get;}` in the interface.
2. A default implementation that returns false. The default state of an implementation is online, and this would basically only exist to keep compilation.
3. Implement `Offline` for the LdClient.
4. Comment on `IsOffline` to indicate that `Offline` is preferred.

Does that sound reasonable to you?

If so, then I would welcome a PR, or we will eventually add it to our backlog.

Thanks,
Ryan

_Filed internally as 195936_

**Comment by justindbaur** [comment]
Thanks for the quick response, @kinyoklion. I just tried implementing it and ran into a roadblock. Default interface implementations are only available in C# 8.0+ and the SDK is targeting 7.3 currently. Does that change whether or not you want to move forward with this?

If you do want to move forward with it, any thoughts on making `IsOffline()` decorated with the [`[EditorBrowsable(EditorBrowsableState.Never)]`](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute?view=net-8.0#remarks)? This wouldn't deprecate it and wouldn't break anyone's implementation but would help deter any new people using it.

**Comment by kinyoklion** [comment]
@justindbaur 

Ah, the default implementations thing is going to be a bit of a problem. We would consider adding a new method to the interface to be a breaking change. Which means we would generally hold off until we have a reason to do a major version (this alone not being enough of a reason).

Similarly increasing our C# would also be problematic to do outside a major version, and we generally try to keep it somewhat low for the widest compatibility.

**Comment by justindbaur** [comment]
@kinyoklion 

I understand, if you'd like to let me know when other breaking changes start dropping in preparation for a major release I can work implement this then.

**Comment by kinyoklion** [comment]
@justindbaur 

Thank you. I will keep that in mind. It may be a bit, because we just recently released a major version.

**Comment by kinyoklion** [comment]
@justindbaur We released a new major version that includes this. Let me know if you encounter other issues.

Thanks,
Ryan
