### ISSUE TITLE
Feature flag configured as bool evaluated incorrectly

### ISSUE THREAD

**Issue by matheuswanted** [launchdarkly/dotnet-server-sdk#180]
**Describe the bug**
In my setup I have two environments(Test and Production), and one flag called `AwardVendors` created as a boolean flag. In my code I'm using the `BoolVariation` method to retrieve the code and it works perfectly fine in the `Test` environment, we turned on the flag last week and noticed the boolvariation was not working with the Production environment but instead the `StringVariation` worked with that same flag.

I even recreated the falg to see if the problem went away but still happens. I just updated the version of the sdk and it still happens.

**To reproduce**
How the feature flag is setup:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/460e4644-101d-4450-af1e-467cdac8b14c)
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/11a3cc16-f055-4116-859e-f6b96aa07377)
Some screenshots of my code:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/fb2a69a1-b7bc-40cc-b647-07de1d9eaa80)

This is test I made to validate the usage of these methods:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/94dabbd4-9a8d-4fbb-9a8e-7a39f2ead0ce)

And this is the output of that test for production:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/e23660c8-a214-4098-94a1-25f6d78e74ea)

And this is the output in test environment:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/cda31c37-1161-4d76-ad39-6e8ec3adb027)

**Expected behavior**
BoolVariation should return the correct bool value in both production and test environments.

**Logs**
```
{
    "@t": "2023-10-17T19:37:50.7754719Z",
    "@m": "Expected type Bool but got String when evaluating feature flag \"\"AwardVendor\"\"; returning default value",
    "@i": "4876cae1",
    "@l": "Error",
    "0": "Bool",
    "1": "String",
    "2": "AwardVendor",
    "SourceContext": "LaunchDarkly.Sdk.Evaluation",
    "ActionId": "ffbc0b0d-e279-40b1-ac89-eba04f3e3346",
}
```

**SDK version**
```
<PackageReference Include="LaunchDarkly.ServerSdk" Version="8.0.0" />
```

**Language version, developer tools**
c# .net core 7.0.402

**OS/platform**
AWS Fargate linux 1.4.0

**Additional context**
Temporary solution:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/e0a11784-2a20-4370-ae52-d4443390f5af)

**Comment by kinyoklion** [comment]
Hello @matheuswanted,

Could you please screenshot the "variations" tab of each of these flags.

Strings and booleans are different in the JSON. For instance `value: true` is a boolean, but `value: "true"` is a string.

Based on your description it would appear that one of your flags was created as a string flag and not a boolean flag. The SDK does not interpret string flags as if they are booleans.

Example of a string flag that happens to contain "true" and "false".

You can see the "string" tag after the "Variations" header.
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/4955475/e4bc891f-c14d-4a5d-a878-6f6a02026052)

Thank you,
Ryan

**Comment by kinyoklion** [comment]
If they are in the same project, then some additional investigation may be needed, but I would still request a view of the variations of each.

**Comment by matheuswanted** [comment]
Hey, thanks for the fast reply! here goes the screenshots, but they're in the same project and both with variation boolean.
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/8536b9a0-3ecc-4344-9c17-fa17c3c9d7c2)
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/97885ed0-ce5d-47aa-b443-2ae20fde0907)
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/83b9a992-d48c-4b2b-b6c6-00faed6b54eb)

**Comment by kinyoklion** [comment]
One more question @matheuswanted.

Are the two evaluations, one against production and the other against test, executing on the same physical machine?

Thank you,
Ryan

**Comment by matheuswanted** [comment]
Hey @kinyoklion,

today the evaluations are different environments, I got the logs and responses from both our application in the test environment and prod environment. They should be very similar though, since we use aws cdk to deploy any change to the infrastructure.

I'll do both checks from my own machine to see if there is any difference. 

We do have a js sdk in our front end application and this is what I found in the network for the prod environment:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/92ab68ae-4d65-442f-a057-af6796dccab7)

the network for the test environment:
![image](https://github.com/launchdarkly/dotnet-server-sdk/assets/19437749/c65dd23a-ff94-4aa6-9bc7-58cbd2282b26)

**Comment by matheuswanted** [comment]
This is awkward 😅

I was reviewing the credentials and noticed we were in offline mode in production, the flag was loaded from the json file for tests😅

Thank you for being so thoughtful and responsive with this issue, I really appreciate it!
