### ISSUE TITLE
Dead link in the readme

### ISSUE THREAD

**Issue by jcmrva** [launchdarkly/dotnet-server-sdk#181]
The [complete reference guide for this SDK](https://docs.launchdarkly.com/docs/dotnet-sdk-reference) url in the readme returns a 404.

https://github.com/launchdarkly/dotnet-server-sdk/blob/8dfe15c7ec13311187e695ef0e669544647ab5aa/README.md?plain=1#L54

**Comment by kinyoklion** [comment]
Fixed on the main branch. Thank you for bringing this up.
