### ISSUE TITLE
.NET 8.0 - Timeout encountered waiting for LaunchDarkly client initialization

### ISSUE THREAD

**Issue by owenashurst** [launchdarkly/dotnet-server-sdk#220]
**Describe the bug**
When creating an LdClient with a Server SDK key, it never seems to initialise despite receiving a 200 status code.

Attempting to troubleshoot network issues, I tried connecting via `https://stream.launchdarkly.com/all` using cURL as per the documentation and it works fine.

**To reproduce**
```
var config = LaunchDarkly.Sdk.Server.Configuration.Builder("sdk-keyhere")
  .Logging(
	  Components.Logging(Logs.ToWriter(Console.Out)).Level(LaunchDarkly.Logging.LogLevel.Debug)
  )
  .Build();

var ldClient = new LdClient(config);
```

Observe the log.

**Expected behavior**
It should connect and initialise properly.

**Logs**
[LaunchDarkly.Sdk] INFO: Starting LaunchDarkly client 8.5.0+bfed72d310097f837df75cebaa19b1d03bda6aa7
[LaunchDarkly.Sdk.DataSource] INFO: Connecting to LaunchDarkly stream
[LaunchDarkly.Sdk] INFO: Waiting up to 10000 milliseconds for LaunchDarkly client to start.
[LaunchDarkly.Sdk.DataSource] DEBUG: Making GET request to EventSource URI https://stream.launchdarkly.com/all
[LaunchDarkly.Sdk.Events] DEBUG: Submitting diagnostic event to https://events.launchdarkly.com/diagnostic with json: JSON here...
[LaunchDarkly.Sdk.Events] DEBUG: Event delivery took 0 ms, response status 202
[LaunchDarkly.Sdk] WARN: Timeout encountered waiting for LaunchDarkly client initialization
[LaunchDarkly.Sdk.DataSource] DEBUG: Cancelling current request
[LaunchDarkly.Sdk.DataSource] DEBUG: Close(Closed) - state was Connecting
[LaunchDarkly.Sdk.DataSource] INFO: Waiting 609 milliseconds before reconnecting...
[LaunchDarkly.Sdk.DataSource] DEBUG: Making GET request to EventSource URI https://stream.launchdarkly.com/all
[LaunchDarkly.Sdk.DataSource] DEBUG: Cancelling current request
[LaunchDarkly.Sdk.DataSource] DEBUG: Close(Closed) - state was Connecting
[LaunchDarkly.Sdk.DataSource] INFO: Waiting 1880 milliseconds before reconnecting...
[LaunchDarkly.Sdk.DataSource] DEBUG: Making GET request to EventSource URI https://stream.launchdarkly.com/all
[LaunchDarkly.Sdk.DataSource] DEBUG: Cancelling current request
[LaunchDarkly.Sdk.DataSource] DEBUG: Close(Closed) - state was Connecting
[LaunchDarkly.Sdk.DataSource] INFO: Waiting 2408 milliseconds before reconnecting...

**SDK version**
LaunchDarkly.ServerSdk 8.5.0

**Language version, developer tools**
.NET 8.0

**OS/platform**
Windows Server (VM in Azure)

**Comment by tanderson-ld** [comment]
Hi @owenashurst, thank you for opening a ticket with this issue.  We'll try to get things figured out.  Are you referring to the 202 in the logs?  That 202 is for events which is a one way communication between the SDK and our servers for reporting events.

If not that 202, when you say "despite receiving a 200 status code", how are you confirming that the SDK is getting a 200? 

The lines starting with `LaunchDarkly.Sdk.DataSource` indicate that the streaming data source is unable to successfully connect to the LaunchDarkly servers to retrieve flag data.

**Comment by owenashurst** [comment]
Hi @tanderson-ld,

I tried instantiating `LdClient` separately from my work machine on my personal laptop and it seemed to connect fine indicating the issue is isolated to our work network. However, I did test the cURL from the same machine at work it was struggling to connect to, and it returned absolutely fine which was quite strange, including the feature flags. Are there anymore URL's I could test out of curiosity so I can isolate it and feed back to my I.T team?

The only URL I tested was `https://stream.launchdarkly.com/all` from here:
https://support.launchdarkly.com/hc/en-us/articles/12190665494811-How-to-check-network-connectivity-using-cURL~

Thanks.

**Comment by tanderson-ld** [comment]
I am not privy to our current best practices with respect to networking configuration.  The SDK connects to several endpoints all on the `launchdarkly.com` domain which you can see [here](https://github.com/launchdarkly/dotnet-server-sdk/blob/bfed72d310097f837df75cebaa19b1d03bda6aa7/pkgs/sdk/server/src/Internal/StandardEndpoints.cs#L10).  If your IT team would like more help, our Support Team is available.  You can open a ticket [here](https://support.launchdarkly.com/hc/en-us/requests/new).

**Comment by owenashurst** [comment]
Thanks @tanderson-ld i'll close the ticket.
